#%RAML 1.0 DataType
type: object
properties:
  "type":
    type: string  | nil
    required: true
  "id":
    type: string  | nil
    required: true
  "name":
    type: string  | nil
    required: true
  "datetime":
    type: date-only  | nil
    required: false